import { Navbar } from '@/components';
import ReactQueryProvider from '@/providers/ReactQueryProvider';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import '../styles/globals.scss';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Warehouse Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <ReactQueryProvider>
          <ToastContainer />
          <div className="min-h-screen bg-zinc-100">
            <Navbar />
            <div className="container py-6">{children}</div>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
